# Generated by Django 5.0.4 on 2024-04-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
