# Generated by Django 5.0.4 on 2024-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_category_description_alter_shoe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
