# Generated by Django 5.0.4 on 2024-04-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_shoe_size_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.shoe')),
            ],
        ),
    ]
