# Generated by Django 5.0.4 on 2024-05-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_shoeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='mysite.shoe'),
        ),
    ]
