# Generated by Django 5.0.4 on 2024-05-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
